// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: k31.proto
// </auto-generated>
// Original file comments:
// Copyright 2019 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace K31Grpcsrv {
  public static partial class PipeTracking
  {
    static readonly string __ServiceName = "K31_grpcsrv.PipeTracking";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::K31Grpcsrv.CaptureFilter> __Marshaller_K31_grpcsrv_CaptureFilter = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::K31Grpcsrv.CaptureFilter.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::K31Grpcsrv.CaptureSignal> __Marshaller_K31_grpcsrv_CaptureSignal = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::K31Grpcsrv.CaptureSignal.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::K31Grpcsrv.OcrResult> __Marshaller_K31_grpcsrv_OcrResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::K31Grpcsrv.OcrResult.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::K31Grpcsrv.ProductionData> __Marshaller_K31_grpcsrv_ProductionData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::K31Grpcsrv.ProductionData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::K31Grpcsrv.SituationData> __Marshaller_K31_grpcsrv_SituationData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::K31Grpcsrv.SituationData.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::K31Grpcsrv.CaptureFilter, global::K31Grpcsrv.CaptureSignal> __Method_GetSignal = new grpc::Method<global::K31Grpcsrv.CaptureFilter, global::K31Grpcsrv.CaptureSignal>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetSignal",
        __Marshaller_K31_grpcsrv_CaptureFilter,
        __Marshaller_K31_grpcsrv_CaptureSignal);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::K31Grpcsrv.OcrResult, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SendResult = new grpc::Method<global::K31Grpcsrv.OcrResult, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendResult",
        __Marshaller_K31_grpcsrv_OcrResult,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::K31Grpcsrv.ProductionData> __Method_UpdatePLCData = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::K31Grpcsrv.ProductionData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "UpdatePLCData",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_K31_grpcsrv_ProductionData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::K31Grpcsrv.SituationData, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SendPositionData = new grpc::Method<global::K31Grpcsrv.SituationData, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SendPositionData",
        __Marshaller_K31_grpcsrv_SituationData,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::K31Grpcsrv.K31Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PipeTracking</summary>
    [grpc::BindServiceMethod(typeof(PipeTracking), "BindService")]
    public abstract partial class PipeTrackingBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetSignal(global::K31Grpcsrv.CaptureFilter request, grpc::IServerStreamWriter<global::K31Grpcsrv.CaptureSignal> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SendResult(global::K31Grpcsrv.OcrResult request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task UpdatePLCData(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::K31Grpcsrv.ProductionData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SendPositionData(grpc::IAsyncStreamReader<global::K31Grpcsrv.SituationData> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PipeTracking</summary>
    public partial class PipeTrackingClient : grpc::ClientBase<PipeTrackingClient>
    {
      /// <summary>Creates a new client for PipeTracking</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PipeTrackingClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PipeTracking that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PipeTrackingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PipeTrackingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PipeTrackingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::K31Grpcsrv.CaptureSignal> GetSignal(global::K31Grpcsrv.CaptureFilter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSignal(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::K31Grpcsrv.CaptureSignal> GetSignal(global::K31Grpcsrv.CaptureFilter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetSignal, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SendResult(global::K31Grpcsrv.OcrResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendResult(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SendResult(global::K31Grpcsrv.OcrResult request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendResult, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SendResultAsync(global::K31Grpcsrv.OcrResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendResultAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SendResultAsync(global::K31Grpcsrv.OcrResult request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendResult, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::K31Grpcsrv.ProductionData> UpdatePLCData(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePLCData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::K31Grpcsrv.ProductionData> UpdatePLCData(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_UpdatePLCData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::K31Grpcsrv.SituationData, global::Google.Protobuf.WellKnownTypes.Empty> SendPositionData(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendPositionData(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::K31Grpcsrv.SituationData, global::Google.Protobuf.WellKnownTypes.Empty> SendPositionData(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SendPositionData, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override PipeTrackingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PipeTrackingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PipeTrackingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSignal, serviceImpl.GetSignal)
          .AddMethod(__Method_SendResult, serviceImpl.SendResult)
          .AddMethod(__Method_UpdatePLCData, serviceImpl.UpdatePLCData)
          .AddMethod(__Method_SendPositionData, serviceImpl.SendPositionData).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PipeTrackingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSignal, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::K31Grpcsrv.CaptureFilter, global::K31Grpcsrv.CaptureSignal>(serviceImpl.GetSignal));
      serviceBinder.AddMethod(__Method_SendResult, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::K31Grpcsrv.OcrResult, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SendResult));
      serviceBinder.AddMethod(__Method_UpdatePLCData, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::K31Grpcsrv.ProductionData>(serviceImpl.UpdatePLCData));
      serviceBinder.AddMethod(__Method_SendPositionData, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::K31Grpcsrv.SituationData, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SendPositionData));
    }

  }
}
#endregion
